stages:
    - build

variables:
    GIT_SUBMODULE_STRATEGY: normal

.build-common:
    stage: build
    except:
        - schedules

.build-docker:
    extends: .build-common
    tags:
        - docker
        - amd64

build-debian:
    extends: .build-docker
    image: registry.videolan.org/vlc-debian-unstable:20210315112333
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos-x86_64:
    extends: .build-common
    tags:
        - old-macmini
    script:
        - export PATH="/Users/videolanci/sandbox/bin:${PATH}"
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos-arm64:
    extends: .build-common
    tags:
        - monterey
    script:
        - export PATH="/Users/videolanci/sandbox/bin:${PATH}"
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win64:
    extends: .build-docker
    image: registry.videolan.org/vlc-debian-win64:20201106143728
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=x86_64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

build-winarm64:
    extends: .build-docker
    image: registry.videolan.org/vlc-debian-llvm-ucrt:20241118101328
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=aarch64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

build-win32:
    extends: .build-docker
    image: registry.videolan.org/vlc-debian-win32:20201106141924
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=i686-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)

pages:
    extends: .build-docker
    image:
        name: registry.videolan.org/vlc-debian-unstable:20210315112333
    script:
        - autoreconf -fisv
        - ./configure
        - make apidoc
        - mv doc/html public
    artifacts:
        paths:
            - public
    only:
        - schedules
    except:
